# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
# https://github.com/marketplace/actions/close-stale-issues
#
# You can adjust the behavior by modifying this file.
# For more information, see: https://github.com/actions/stale
name: Mark stale issues and pull requests
on:
  schedule:
    - cron: '43 1 * * *'
jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      #contents: write  # only for delete-branch option
    steps:
      - uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}                    #PAT for GitHub API authentication
          #stale-issue-message: 'Stale issue'                         #Comment on the staled issues
          #stale-pr-message: 'Stale pull request'                     #Comment on the staled PRs
          stale-issue-label: Stale                                   #Label to apply on staled issues
          stale-pr-label: Stale                                      #Label to apply on staled PRs
          days-before-stale: 30                                      #Idle number of days before marking issues/PRs stale (default: 60)
          #days-before-issue-stale:                                   #Override days-before-stale for issues only
          #days-before-pr-stale:                                      #Override days-before-stale for PRs only
          days-before-close: 90                                      #Idle number of days before closing stale issues/PRs (default: 7)
          #days-before-issue-close:                                   #Override days-before-close for issues only
          #days-before-pr-close:                                      #Override days-before-close for PRs only
          #close-issue-message:                                       #Comment on the staled issues while closed
          #close-pr-message:                                          #Comment on the staled PRs while closed
          close-issue-label: Inactive                                #Label to apply on closed issues
          close-issue-reason: 'Inactivity rule'                      #Reason to use when closing issues (default: not_planned)
          close-pr-label: Inactive                                   #Label to apply on closed PRs
          #exempt-issue-labels:                                       #Labels on issues exempted from stale
          #exempt-pr-labels:                                          #Labels on PRs exempted from stale
          #only-labels:                                               #Only issues/PRs with ALL these labels are checked
          #only-issue-labels:                                         #Override only-labels for issues only
          #only-pr-labels:                                            #Override only-labels for PRs only
          #any-of-labels:                                             #Only issues/PRs with ANY of these labels are checked
          #any-of-issue-labels:                                       #Override any-of-labels for issues only
          #any-of-pr-labels:                                          #Override any-of-labels for PRs only
          operations-per-run: 30                                     #Max number of operations per run
          remove-stale-when-updated: true                            #Remove stale label from issues/PRs on updates
          remove-issue-stale-when-updated: true                      #Remove stale label from issues on updates/comments
          remove-pr-stale-when-updated: true                         #Remove stale label from PRs on updates/comments
          #labels-to-add-when-unstale:                                #Add specified labels from issues/PRs when they become unstale
          #labels-to-remove-when-stale:                               #Remove specified labels from issues/PRs when they become stale
          #labels-to-remove-when-unstale:                             #Remove specified labels from issues/PRs when they become unstale
          debug-only: false                                          #Dry-run
          ascending: false                                           #Order to get issues/PRs
          #start-date:                                                #Skip stale action for issues/PRs created before it
          delete-branch: false                                       #Delete branch after closing a stale PR
          #exempt-milestones:                                         #Milestones on issues/PRs exempted from stale
          #exempt-issue-milestones:                                   #Override exempt-milestones for issues only
          #exempt-pr-milestones:                                      #Override exempt-milestones for PRs only
          exempt-all-milestones: false                               #Exempt all issues/PRs with milestones from stale
          #exempt-all-issue-milestones:                               #Override exempt-all-milestones for issues only
          #exempt-all-pr-milestones:                                  #Override exempt-all-milestones for PRs only
          #exempt-assignees:                                          #Assignees on issues/PRs exempted from stale
          #exempt-issue-assignees:                                    #Override exempt-assignees for issues only
          #exempt-pr-assignees:                                       #Override exempt-assignees for PRs only
          exempt-all-assignees: false                                #Exempt all issues/PRs with assignees from stale
          #exempt-all-issue-assignees:                                #Override exempt-all-assignees for issues only
          #exempt-all-pr-assignees:                                   #Override exempt-all-assignees for PRs only
          #exempt-draft-pr:                                           #Skip the stale action for draft PRs
          #enable-statistics:                                         #Display statistics in the logs
          #ignore-updates:                                            #Any update (update/comment) can reset the stale idle time on the issues/PRs
          #ignore-issue-updates:                                      #Override ignore-updates for issues only
          #ignore-pr-updates:                                         #Override ignore-updates for PRs only
          #include-only-assigned:                                     #Process only assigned issues
